services:
  backend:
    image: test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8181"
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
    ports:
      - "5400:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql