spring.application.name: ApplicationService
server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://database:5432/test
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver